CREATE(:Candidate {Name: "Shane Cassells",Votes:"10585",Gender:"Male",Party:"FF",Won:"MW"}),
(:Candidate {Name: "Peadar Toibin",Votes:"9442",Gender:"Male",Party:"SF",Won:"MW"}),
(:Candidate {Name: "Damien English",Votes:"8123",Gender:"Male",Party:"FG",Won:"MW"}),
(:Candidate {Name: "Ray Butler",Votes:"4432",Gender:"Male",Party:"FG"}),
(:Candidate {Name: "Trevor Golden",Votes:"1718",Gender:"Male",Party:"Ind"}),
(:Candidate {Name: "Seamus McMenamin",Votes:"1421",Gender:"Male",Party:"GP"}),
(:Candidate {Name: "Alan Lawes",Votes:"1279",Gender:"Male",Party:"DDI"}),
(:Candidate {Name: "Tracy McElhinney",Votes:"1166",Gender:"Female",Party:"Lab"}),
(:Candidate {Name: "John Malone",Votes:"439",Gender:"Male",Party:"Ind"});
