CREATE(:Candidate {Name: "Shane Cassells",Votes:"10585",Gender:"Male",Party:""}),
(:Candidate {Name: "Peadar Toibin",Votes:"9442",Gender:"Male",Party:""}),
(:Candidate {Name: "Damien English",Votes:"8123",Gender:"Male",Party:""}),
(:Candidate {Name: "Ray Butler",Votes:"4432",Gender:"Male",Party:""}),
(:Candidate {Name: "Trevor Golden",Votes:"1718",Gender:"Male",Party:""}),
(:Candidate {Name: "Seamus McMenamin",Votes:"1421",Gender:"Male",Party:""}),
(:Candidate {Name: "Alan Lawes",Votes:"1279",Gender:"Male",Party:""}),
(:Candidate {Name: "Tracy McElhinney",Votes:"1166",Gender:"Female",Party:""}),
(:Candidate {Name: "John Malone",Votes:"439",Gender:"Male",Party:""});
